version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - server
    restart: unless-stopped
    networks:
      - fitfusion-dev

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./server:/app
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
      - DEBUG=True
      - SECRET_KEY=dev_secret_key_replace_in_production
      - ALLOWED_HOSTS=localhost,127.0.0.1
      - CORS_ALLOWED_ORIGINS=http://localhost:3000
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=postgres://postgres:postgres@db:5432/fitfusion
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - fitfusion-dev

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fitfusion
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - fitfusion-dev

volumes:
  postgres_data:

networks:
  fitfusion-dev:
    driver: bridge 