version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      target: production
    environment:
      - NODE_ENV=production
      - PORT=3000
      - NEXT_PUBLIC_API_URL=http://server:8000
    networks:
      - fitfusion-prod
    restart: unless-stopped

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
      target: production
    environment:
      - ENVIRONMENT=production
      - DEBUG=False
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS},server
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS},http://client:3000
      - DATABASE_URL=${DATABASE_URL}
      - SECURE_SSL_REDIRECT=${SECURE_SSL_REDIRECT:-True}
    networks:
      - fitfusion-prod
    restart: unless-stopped

  nginx:
    image: nginx:1.25-alpine
    ports:
      - "80:8080"
      - "443:8443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./client/public:/app/client/public
      - static_volume:/app/server/staticfiles
    depends_on:
      - client
      - server
    networks:
      - fitfusion-prod
    restart: unless-stopped

volumes:
  static_volume:

networks:
  fitfusion-prod:
    driver: bridge 