services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://server:8000
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
    entrypoint: ["sh", "-c", "npm install && npm run dev"]
    depends_on:
      - server
    restart: unless-stopped
    networks:
      - fitfusion-dev

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - ./server:/app
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/fitfusion
      - SECRET_KEY=dev_secret_key_replace_in_production
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=60
      - HOST=0.0.0.0
      - PORT=8000
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - fitfusion-dev

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fitfusion
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - fitfusion-dev

volumes:
  postgres_data:

networks:
  fitfusion-dev:
    driver: bridge 